name: PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, gd, pdo_mysql
          coverage: phpunit
          tools: phpunit, composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check Database Connection
        run: |
          sudo apt-get install -y mariadb-client
          mysql --host 161.132.49.95 --port 3306 --user=escobar --password=Upt2024 --execute="SHOW DATABASES;"
          
      - name: Set Execute Permission for PHPUnit
        run: chmod +x vendor/bin/phpunit
        
      - name: Run tests with coverage report
        env:
          DB_HOST: 161.132.49.95
          DB_USER: escobar
          DB_PASS: Upt2024
          DB_NAME: sis_venta_test
        run: ./vendor/bin/phpunit --configuration phpunit.xml --coverage-html build/coverage

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/coverage/
